fineract:
  datasource:
    core:
      host: operations-mysql
      port: 3306
      schema: tenants
      username: root
      password: mysql
    common:
      protocol: jdbc
      subprotocol: mysql
      driverclass_name: com.mysql.cj.jdbc.Driver

token:
  user:
    access-validity-seconds: 600
    refresh-validity-seconds: 43200
  client:
    access-validity-seconds: 3600

config:
  imu:
    rate-validity-seconds: 300

caching:
  enabled: false

security:
  filter-order: 5

spring:
  resources:
    add-mappings: false
  mvc:
    favicon:
      enabled: false
  jmx:
    enabled: false

server:
  port: 5000

rest:
  authorization:
    enabled: true
    settings:
      - endpoint: "/api/v1/transfer/*/refund"
        authority: "hasAuthority('REFUND')"
      - endpoint: "/api/v1/**"
        authority: "hasAuthority('ALL_FUNCTIONS')"
logging:
  level:
    ROOT: ERROR

cloud:
  aws:
    enabled: true
    credentials:
      access-key: ${AWS_ACCESS_KEY:AKIAX32JM37TZOJ5AKFB}
      secret-key: ${AWS_SECRET_KEY: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}
    region:
      static: us-east-2
    stack:
      auto: false
  azure:
    enabled: false
    blob:
      connection-string:

application:
  bucket-name: paymenthub-ee-dev
